#!/bin/bash

cp -r ~/Themes/Carbon/. ~/ &&
wal -i ~/Wallpaper/a_road_going_through_a_desert.jpeg && wal --theme ~/.cache/wal/e-ink.json
qtile cmd-obj -o cmd -f restart &&
~/.spicetify/spicetify apply &&
pkill dunst && dunst &
