#!/bin/bash

cp -r ~/Themes/Cozy/. ~/ &&
wal -b 282738 -i ~/Wallpaper/Aesthetic2.png &&
(echo -e "[Theme]\nCurrent=Cozy" | sudo -n tee /etc/sddm.conf.d/theme.conf || true) &&
qtile cmd-obj -o cmd -f restart
spicetify apply || true
pkill dunst && dunst & 
