#!/usr/bin/env bash

# ───────────────────────────────────────────────────────────────
#                      Theme Settings
# ───────────────────────────────────────────────────────────────
dir="$HOME/.config/rofi/settings/theme_switcher/"

# ───────────────────────────────────────────────────────────────
#                         Menu Options
# ───────────────────────────────────────────────────────────────
theme1='Cozy'
theme2='Sakura'
theme3='Natura'
theme4='Everforest'

# ───────────────────────────────────────────────────────────────
#                           User Info
# ───────────────────────────────────────────────────────────────
username=" $(whoami)"
messages=("Which theme do you want?" "Select a theme to apply!" "Choose your preferred theme!")

# Pick a random message
sendoff="${messages[$((RANDOM % ${#messages[@]}))]}"

# ───────────────────────────────────────────────────────────────
#                           Rofi Cmd
# ───────────────────────────────────────────────────────────────
rofi_cmd() {
    rofi -dmenu \
        -p "$username" \
        -mesg "$sendoff" \
        -theme ${dir}/everforest.rasi
}

# ───────────────────────────────────────────────────────────────
#                       Run Rofi Menu
# ───────────────────────────────────────────────────────────────
run_rofi() {
    echo -e "$theme1\n$theme2\n$theme3\n$theme4" | rofi_cmd
}

# ───────────────────────────────────────────────────────────────
#                        Command Exec
# ───────────────────────────────────────────────────────────────
run_cmd() {
    case $1 in
        "$theme1")
            ~/.config/rofi/theme_scripts/Cozy
            ;;
        "$theme2")
            ~/.config/rofi/theme_scripts/Sakura
            ;;
        "$theme3")
            ~/.config/rofi/theme_scripts/Natura
            ;;
        "$theme4")
            ~/.config/rofi/theme_scripts/Everforest
            ;;
    esac
}

# ───────────────────────────────────────────────────────────────
#                           Execute Cmd
# ───────────────────────────────────────────────────────────────
chosen="$(run_rofi)"
run_cmd "$chosen"
