[colors.bright]
black = "#50545B"
blue = "#6CB8F9"
cyan = "#5FC0CC"
green = "#A2CD83"
magenta = "#D282E7"
red = "#EA757E"
white = "#B5BCC9"
yellow = "#EFCA84"

[colors.normal]
black = "#32363D"
blue = "#62AEEF"
cyan = "#55B6C2"
green = "#98C379"
magenta = "#C778DD"
red = "#E06B74"
white = "#ABB2BF"
yellow = "#E5C07A"

[colors.primary]
background = "#1E2128"
foreground = "#ABB2BF"
