[font]
<<<<<<< HEAD
size = 11
=======
size = 9
>>>>>>> 59c16d9292c711cd50974fcaede9d2e007f24440

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
