#!/bin/bash

sed -i "\$s/.*/colors = Cozy/" "$HOME/dotfiles/.config/qtile/Settings/pallete.py"
cp -r $HOME/.local/.Themes/Cozy/. $HOME/dotfiles &&
feh --bg-scale $HOME/.local/.Wallpaper/Cozy.jpg &&
sed -i '$s/.*/feh --bg-scale "$HOME\/dotfiles\/.Wallpaper\/Cozy.jpg"/' "$HOME/dotfiles/.config/qtile/autostart_once.sh" 
qtile cmd-obj -o cmd -f restart 

