#!/bin/bash

sed -i "\$s/.*/colors = Natura/" "$HOME/dotfiles/.config/qtile/Settings/pallete.py"
cp -r $HOME/.local/.Themes/Natura/. $HOME/dotfiles &&
feh --bg-scale $HOME/.local/.Wallpaper/Natura.jpg &&
sed -i '$s/.*/feh --bg-scale "$HOME\/dotfiles\/.Wallpaper\/Natura.jpg"/' "$HOME/dotfiles/.config/qtile/autostart_once.sh" 
qtile cmd-obj -o cmd -f restart 

