#!/bin/bash

sed -i "\$s/.*/colors = Sakura/" "$HOME/dotfiles/.config/qtile/Settings/pallete.py"
cp -r $HOME/.local/.Themes/Sakura/. $HOME/dotfiles &&
feh --bg-scale $HOME/.local/.Wallpaper/Sakura.jpg &&
sed -i '$s/.*/feh --bg-scale "$HOME\/dotfiles\/.Wallpaper\/Sakura.jpg"/' "$HOME/dotfiles/.config/qtile/autostart_once.sh" 
qtile cmd-obj -o cmd -f restart 


