#!/bin/bash

options=("󱄖 Cozy" "󰞇 Sakura" "󰌪 Natura" "󱢗 Everforest")
selected=$(printf '%s\n' "${options[@]}" | rofi -dmenu -l 4 -i -mesg "T H E M E S")

case $selected in
    "󱄖 Cozy")
      sh $HOME/.config/rofi/scripts/Cozy
        ;;
    "󰞇 Sakura")
      sh $HOME/.config/rofi/scripts/Sakura
        ;;
    "󰌪 Natura")
      sh $HOME/.config/rofi/scripts/Natura
        ;;
    "󱢗 Everforest")
      sh $HOME/.config/rofi/scripts/Everforest
        ;;
    *)
        ;;
esac
